Region: us-east-2
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.small
  Networking:
    SubnetId: subnet-0e5e9e09eaa14d678
  Ssh:
    KeyName: us-east-2
  Imds:
    Secured: false
Scheduling:
  Scheduler: awsbatch
  AwsBatchQueues:
  - Name: queue1
    ComputeResources:
    - Name: optimal
      InstanceTypes:
      - optimal
      MinvCpus: 0
      DesiredvCpus: 0
      MaxvCpus: 8
    Networking:
      SubnetIds:
      - subnet-0f93eb66d6fe88a1e
