Region: us-east-2
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.small
  Networking:
    SubnetId: subnet-03019ca9abfb2e087
  Ssh:
    KeyName: us-east-2
  Imds:
    Secured: false
Scheduling:
  Scheduler: awsbatch
  AwsBatchQueues:
  - Name: queue1
    ComputeResources:
    - Name: optimal
      InstanceTypes:
      - optimal
      MinvCpus: 0
      DesiredvCpus: 0
      MaxvCpus: 16
    Networking:
      SubnetIds:
      - subnet-0c7cd388eb724a1f3
