# pcluster create-cluster --cluster-name batch-pcluster --cluster-configuration batch-cluster-config.yaml --region us-east-2
# pcluster describe-cluster --cluster-name batch-pcluster --region us-east-2
# pcluster ssh --cluster-name batch-pcluster --region us-east-2 -i /Users/dubaria/Desktop/Keys/us-east-2.pem
# pcluster delete-cluster --region us-east-2 --cluster-name batch-pcluster








#####
# pcluster describe-cluster-instances -n batch-pcluster -r us-east-2
# scp -i /Users/dubaria/Desktop/Keys/us-east-2.pem /Users/dubaria/Desktop/Exercises/ParallelCluster/Batch-files/* ec2-user@3.14.130.120:/home/ec2-user
# pcluster ssh --cluster-name batch-pcluster --region us-east-2 -i /Users/dubaria/Desktop/Keys/us-east-2.pem


## https://docs.aws.amazon.com/parallelcluster/latest/ug/awsbatchcli-v3.html
# awsbsub -n 3 -cf submit_mpi.sh
# awsbhosts
# awsbhosts -d
# watch awsbstat -d
# awsbstat -s ALL
# awsbstat -s ALL -e
# awsbout 28bc9514-bc20-40f5-8c0d-48ba1ac0af3a#0
# awsbout 28bc9514-bc20-40f5-8c0d-48ba1ac0af3a#1
# awsbout 28bc9514-bc20-40f5-8c0d-48ba1ac0af3a#2
# awsbout 28bc9514-bc20-40f5-8c0d-48ba1ac0af3a#0 -s 
# awsbout 28bc9514-bc20-40f5-8c0d-48ba1ac0af3a#1 -s
# awsbout 28bc9514-bc20-40f5-8c0d-48ba1ac0af3a#2 -s


Region: us-east-2
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.medium
  Networking:
    SubnetId: subnet-0dfa7d55715afb546
  Ssh:
    KeyName: us-east-2
  Imds:
    Secured: false
Scheduling:
  Scheduler: awsbatch
  AwsBatchQueues:
    - Name: queue1
      ComputeResources:
        - Name: optimal
          InstanceTypes:
            - optimal
          MinvCpus: 0
          DesiredvCpus: 0
          MaxvCpus: 10
      Networking:
        SubnetIds:
          - subnet-01f6f9884897e841c
          # - subnet-016aa46b652c4d67e
          # - subnet-04c54c027909e09d5
